version: '3'
services:
  oracle:
    container_name: oracledb
    image: store/oracle/database-enterprise:12.2.0.1
    ports:
      - 1521:1521
      - 5500:5500
#      - 8080:8080 #Oracle APEX tool
    volumes:
      - "./data/oracle:/ORCL"
    env_file:
      - "docker/ora.conf"
